modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/Pitan76/MCPitanLib/issue"

[[mods]]
modId = "mcpitanlib"
version = "${version}"
displayName = "MCPitanLib"
#updateJSONURL="http://myurl.me/"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/mcpitanlibarch"
logoFile = "icon.png"
authors = "Pitan"
description = '''
Pitan's Minecraft Mod Library
'''

[[dependencies.mcpitanlib]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcpitanlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcpitanlib]]
modId = "architectury"
mandatory = true
versionRange = "[1.3.80,)"
ordering = "NONE"
side = "BOTH"