plugins {
    id "architectury-plugin" version "3.5-SNAPSHOT"
    id "dev.architectury.loom-no-remap" version "1.14-SNAPSHOT" apply false
    id "me.modmuss50.mod-publish-plugin" version "2.2.0" apply false
    id "com.gradleup.shadow" version "9.4.0"
}

architectury {
    minecraft = rootProject.minecraft_version
}

def loadProperties(filename) {
    def props = new Properties()
    file(filename).withInputStream {
        props.load(it)
    }
    return props
}

ext.info = loadProperties("$rootDir/info.properties")

allprojects {
    version = info.mod_version + "-" + rootProject.minecraft_version
    group = info.maven_group
}

subprojects {
    apply plugin: "architectury-plugin"
    apply plugin: "dev.architectury.loom-no-remap"
    apply plugin: "maven-publish"
    apply plugin: "com.gradleup.shadow"

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = info.archives_base_name
    }

    repositories {
        maven { url "https://maven.pitan76.net/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.shedaniel.me/" }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

        // https://mvnrepository.com/artifact/org.yaml/snakeyaml
        implementation 'org.yaml:snakeyaml:2.0'
    }

    if (name in "fabric,neoforge".split(",")) {
        apply plugin: "me.modmuss50.mod-publish-plugin"

        publishMods {
            file = tasks.named("shadowJar").flatMap { it.archiveFile }
            version = info.mod_version + "-" + name + "-" + rootProject.minecraft_version
            displayName = info.archives_base_name + " " + info.mod_version + " (" + name + " " + rootProject.minecraft_version + ")"
            changelog = info.changelog
            type = BETA
            modLoaders.add(name)

            if (providers.environmentVariable("CURSEFORGE_TOKEN").isPresent()) {
                curseforge {
                    accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
                    projectId = "682213"
                    minecraftVersions.add(rootProject.minecraft_version)

                    client = true
                    server = true

                    if (name == "fabric") {
                        requires("fabric-api")
                    }
                    embeds("cloth-config", "compatdatapacks", "legacyitemmodels")
                }
            }

            if (providers.environmentVariable("MODRINTH_TOKEN").isPresent()) {
                modrinth {
                    accessToken = providers.environmentVariable("MODRINTH_TOKEN")
                    projectId = "mcpitanlibarch"
                    minecraftVersions.add(rootProject.minecraft_version)

                    if (name == "fabric") {
                        requires("fabric-api")
                    }
                    embeds("cloth-config", "compatdatapacks", "legacyitemmodels")
                }
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    java {
        withSourcesJar()
    }
}