plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.14-SNAPSHOT" apply false
    id 'com.matthewprenger.cursegradle' version '1.5.0'
    id "com.modrinth.minotaur" version "2.+"
}

architectury {
    minecraft = rootProject.minecraft_version
}

def loadProperties(filename) {
    def props = new Properties()
    file(filename).withInputStream {
        props.load(it)
    }
    return props
}

ext.info = loadProperties("$rootDir/info.properties")

allprojects {
    version = info.mod_version + "-" + rootProject.minecraft_version
    group = info.maven_group
}

subprojects {
    apply plugin: "architectury-plugin"
    apply plugin: "dev.architectury.loom"
    apply plugin: "maven-publish"
    apply plugin: "com.modrinth.minotaur"
    apply plugin: "com.matthewprenger.cursegradle"

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = info.archives_base_name
    }

    loom {
        silentMojangMappingsLicense()
    }

    repositories {
        maven { url "https://maven.pitan76.net/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.shedaniel.me/" }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

        // https://mvnrepository.com/artifact/org.yaml/snakeyaml
        implementation 'org.yaml:snakeyaml:2.0'
    }

    if (name in "fabric,neoforge".split(",")) {
        var modLoader = name

        if (System.getenv("CURSEFORGE_TOKEN") != null) {
            curseforge {
                apiKey = System.getenv("CURSEFORGE_TOKEN")
                project {
                    id = '682213'
                    changelog = info.changelog
                    releaseType = 'beta'
                    if (modLoader == "fabric") {
                        addGameVersion "Fabric"
                    }
                    if (modLoader == "forge") {
                        addGameVersion "Forge"
                    }
                    if (modLoader == "neoforge") {
                        addGameVersion "NeoForge"
                    }
                    addGameVersion '26.1'

                    relations {
                        if (modLoader == "fabric") {
                            requiredDependency "fabric-api"
                        }

//                        requiredDependency 'architectury-api'
//                        embeddedLibrary 'cloth-config'
                        embeddedLibrary 'compatdatapacks'
                        embeddedLibrary 'legacyitemmodels'
                    }

                    mainArtifact(tasks.remapJar)
                }
                options {
                    forgeGradleIntegration = false
                }
            }

        }

        if (System.getenv("MODRINTH_TOKEN") != null) {
            modrinth {
                token = System.getenv("MODRINTH_TOKEN")
                projectId = 'mcpitanlibarch'
                versionNumber = info.mod_version + "-" + modLoader
                gameVersions = ['26.1']
                versionType = 'beta'
                uploadFile = tasks.remapJar
                changelog = info.changelog
                loaders = [modLoader]
                dependencies {
                    if (modLoader == "fabric") {
                        required.project "fabric-api" // Fabric API
                    }
//                    required.project "architectury-api"
//                    embedded.project "cloth-config"
                    embedded.project "compatdatapacks"
                    embedded.project "legacyitemmodels"
                }
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 21
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    java {
        withSourcesJar()
    }
}
