org.gradle.jvmargs=-Xmx3G

minecraft_version=26.1
java_version=25

# https://www.curseforge.com/minecraft/mc-mods/architectury-api
#architectury_version=19.0.1

# https://fabricmc.net/develop/
fabric_loader_version=0.18.6
fabric_api_version=0.145.1+26.1
team_reborn_energy_version=5.0.0

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.1-beta

cloth_config_version=26.1.154

# https://maven.pitan76.net/net/pitan76/compatdatapacks76/
compatdatapacks76_version=1.0.18.261-SNAPSHOT
legacyitemmodels_version=1.0.4.261-SNAPSHOT
littleintermediaryfallback_version=1.0.2.261-SNAPSHOT
littleoldnamedfallback_version=1.0.1.261-SNAPSHOT

fabricEnabled=true
neoforgeEnabled=true

publish_jar_task=shadowJar
publish_loaders=fabric,neoforge
game_versions=26.1,26.1.1,26.1.2
# STABLE / BETA / ALPHA
release_type=STABLE
required_deps=
required_deps_fabric=fabric-api
embedded_deps=cloth-config,compatdatapacks,legacyitemmodels

org.gradle.parallel=true
org.gradle.workers.max=4