org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.8

# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=17.0.8

# https://fabricmc.net/develop/
fabric_loader_version=0.17.2
yarn_mappings=1.21.8+build.1
fabric_api_version=0.131.0+1.21.8


# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.8.32

cloth_config_version=19.0.146

# https://maven.pitan76.net/net/pitan76/compatdatapacks76/
compatdatapacks76_version=1.0.14.216
legacyitemmodels_version=1.0.1.214

fabricEnabled=true
neoforgeEnabled=true

org.gradle.parallel=true
org.gradle.workers.max=4