org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.9
java_version=21

# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=18.0.5

# https://fabricmc.net/develop/
fabric_loader_version=0.17.3
yarn_mappings=1.21.9+build.1
fabric_api_version=0.134.1+1.21.9

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.9.16-beta

cloth_config_version=20.0.148

# https://maven.pitan76.net/net/pitan76/compatdatapacks76/
compatdatapacks76_version=1.0.14.216
legacyitemmodels_version=1.0.4.214

fabricEnabled=true
neoforgeEnabled=true

publish_jar_task=remapJar
publish_loaders=fabric,neoforge
game_versions=1.21.9,1.21.10
# STABLE / BETA / ALPHA
release_type=STABLE
required_deps=
required_deps_fabric=fabric-api
embedded_deps=cloth-config,compatdatapacks,legacyitemmodels

org.gradle.parallel=true
org.gradle.workers.max=4