package net.pitan76.mcpitanlib.midohra.entity;

public class EntityTypes {
    public static final EntityTypeWrapper BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.OAK_BOAT);
    public static final EntityTypeWrapper ACACIA_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ACACIA_BOAT);
    public static final EntityTypeWrapper ACACIA_CHEST_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ACACIA_CHEST_BOAT);
    public static final EntityTypeWrapper BIRCH_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.BIRCH_BOAT);
    public static final EntityTypeWrapper BIRCH_CHEST_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.BIRCH_CHEST_BOAT);
    public static final EntityTypeWrapper DARK_OAK_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.DARK_OAK_BOAT);
    public static final EntityTypeWrapper DARK_OAK_CHEST_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.DARK_OAK_CHEST_BOAT);
    public static final EntityTypeWrapper JUNGLE_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.JUNGLE_BOAT);
    public static final EntityTypeWrapper JUNGLE_CHEST_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.JUNGLE_CHEST_BOAT);
    public static final EntityTypeWrapper SPRUCE_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.SPRUCE_BOAT);
    public static final EntityTypeWrapper SPRUCE_CHEST_BOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.SPRUCE_CHEST_BOAT);
    public static final EntityTypeWrapper FURNACE_MINECART = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.FURNACE_MINECART);
    public static final EntityTypeWrapper HOPPER_MINECART = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.HOPPER_MINECART);
    public static final EntityTypeWrapper MINECART = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.MINECART);
    public static final EntityTypeWrapper TNT_MINECART = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.TNT_MINECART);
    public static final EntityTypeWrapper CHEST_MINECART = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.CHEST_MINECART);
    public static final EntityTypeWrapper HORSE = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.HORSE);
    public static final EntityTypeWrapper LLAMA = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.LLAMA);

    public static final EntityTypeWrapper ITEM = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ITEM);
    public static final EntityTypeWrapper ITEM_DISPLAY = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ITEM_DISPLAY);
    public static final EntityTypeWrapper ITEM_FRAME = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ITEM_FRAME);
    public static final EntityTypeWrapper GLOW_ITEM_FRAME = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.GLOW_ITEM_FRAME);
    public static final EntityTypeWrapper EXPERIENCE_BOTTLE = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.EXPERIENCE_BOTTLE);
    public static final EntityTypeWrapper EXPERIENCE_ORB = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.EXPERIENCE_ORB);

    public static final EntityTypeWrapper SNOWBALL = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.SNOWBALL);
    public static final EntityTypeWrapper FIREBALL = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.FIREBALL);
    public static final EntityTypeWrapper SMALL_FIREBALL = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.SMALL_FIREBALL);
    public static final EntityTypeWrapper DRAGON_FIREBALL = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.DRAGON_FIREBALL);
    public static final EntityTypeWrapper FIREWORK_ROCKET = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.FIREWORK_ROCKET);

    public static final EntityTypeWrapper ALLAY = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ALLAY);
    public static final EntityTypeWrapper AXOLOTL = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.AXOLOTL);
    public static final EntityTypeWrapper BAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.BAT);
    public static final EntityTypeWrapper BEE = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.BEE);
    public static final EntityTypeWrapper BLAZE = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.BLAZE);
    public static final EntityTypeWrapper CAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.CAT);
    public static final EntityTypeWrapper CHICKEN = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.CHICKEN);
    public static final EntityTypeWrapper COD = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.COD);
    public static final EntityTypeWrapper COW = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.COW);
    public static final EntityTypeWrapper CREEPER = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.CREEPER);
    public static final EntityTypeWrapper DOLPHIN = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.DOLPHIN);
    public static final EntityTypeWrapper DONKEY = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.DONKEY);
    public static final EntityTypeWrapper DROWNED = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.DROWNED);
    public static final EntityTypeWrapper ELDER_GUARDIAN = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ELDER_GUARDIAN);
    public static final EntityTypeWrapper ENDER_DRAGON = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ENDER_DRAGON);
    public static final EntityTypeWrapper ENDERMAN = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ENDERMAN);
    public static final EntityTypeWrapper ENDERMITE = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ENDERMITE);
    public static final EntityTypeWrapper EVOKER = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.EVOKER);
    public static final EntityTypeWrapper FOX = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.FOX);
    public static final EntityTypeWrapper FROG = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.FROG);
    public static final EntityTypeWrapper GHAST = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.GHAST);
    public static final EntityTypeWrapper GIANT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.GIANT);
    public static final EntityTypeWrapper GLOW_SQUID = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.GLOW_SQUID);
    public static final EntityTypeWrapper GOAT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.GOAT);
    public static final EntityTypeWrapper GUARDIAN = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.GUARDIAN);
    public static final EntityTypeWrapper HUSK = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.HUSK);
    public static final EntityTypeWrapper ILLUSIONER = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ILLUSIONER);
    public static final EntityTypeWrapper IRON_GOLEM = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.IRON_GOLEM);
    public static final EntityTypeWrapper LLAMA_SPIT = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.LLAMA_SPIT);
    public static final EntityTypeWrapper MAGMA_CUBE = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.MAGMA_CUBE);
    public static final EntityTypeWrapper MARKER = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.MARKER);
    public static final EntityTypeWrapper MOOSHROOM = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.MOOSHROOM);
    public static final EntityTypeWrapper MULE = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.MULE);
    public static final EntityTypeWrapper SKELETON = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.SKELETON);
    public static final EntityTypeWrapper VILLAGER = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.VILLAGER);
    public static final EntityTypeWrapper ZOMBIE = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ZOMBIE);
    public static final EntityTypeWrapper ZOMBIE_VILLAGER = EntityTypeWrapper.of(net.minecraft.world.entity.EntityTypes.ZOMBIE_VILLAGER);
}
