dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
}

architectury {
    common("fabric", "neoforge")
}

loom {
    accessWidenerPath = file("src/main/resources/mcpitanlib.accesswidener")
}

tasks.shadowJar {
    enabled = false
}

tasks.jar {
    setArchiveClassifier(null)
}
