plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
}
architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    runs {
        configureEach {
            vmArg "-Dneoforge.warnings.onlyin.hide=true"
        }
    }
    /*
    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "mcpitanlib-common.mixins.json"
        mixinConfig "mcpitanlib.mixins.json"
    }

     */
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    flatDir {
        dirs 'run/mods'
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury-neoforge:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }

    shadowCommon 'org.yaml:snakeyaml:2.0'

    include("me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}")

    include("net.pitan76:compatdatapacks76-neoforge:${rootProject.compatdatapacks76_version}")
    include("net.pitan76:legacyitemmodels-neoforge:${rootProject.legacyitemmodels_version}")

    // Automatically load all local NeoForge mod jars from the run/mods directory in development
    fileTree(dir: 'run/mods', include: '*.jar').each { File file ->
        String nameWithoutExtension = file.name.take(file.name.lastIndexOf('.'))
        modRuntimeOnly name: nameWithoutExtension
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }

    project.version = project.version + "-neoforge"
}

shadowJar {
    relocate "org.yaml.snakeyaml", "net.pitan76.mcpitanlib.shadow.yaml.snakeyaml"

    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set "dev-shadow"
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set null

    atAccessWideners.add(loom.accessWidenerPath.get().asFile.name)
}

jar {
    archiveClassifier.set "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenNeoForge(MavenPublication) {
            artifactId = info.archives_base_name + "-" + project.name + "-" + rootProject.minecraft_version
            version = info.mod_version
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/PTOM76/maven")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}