name: Auto Cherry-Pick
on:
  push:
    branches:
      - "1.*" # 1.21.5, 1.21.4...のブランチでpushされたとき
  pull_request:
    types:
      - closed # PRがmergeされたとき
jobs:
  cherry-pick:
    if: |
      (github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check
        id: check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if echo "$COMMIT_MSG" | grep -q '^\[cp\]'; then
            echo "pickable=true" >> $GITHUB_ENV
          fi
      - name: Setup Git
        if: env.pickable == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Chmod cherry-pick.sh
        if: env.pickable == 'true'
        run: |
          if [ ! -f .github/workflows/cherry-pick.sh ]; then
            echo "cherry-pick.sh not found"
            exit 1
          fi
          git update-index --assume-unchanged .github/workflows/cherry-pick.sh
          chmod +x .github/workflows/cherry-pick.sh
      - name: Run cherry-pick.sh
        if: env.pickable == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/workflows/cherry-pick.sh